name: netflix_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  bloc: ^8.1.2
  bordered_text: ^2.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  google_fonts: ^4.0.4
  injectable: ^1.5.3
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  logger: ^1.3.0
  share_plus: ^7.0.2
  video_player: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  injectable_generator: ^1.5.3

flutter:

  uses-material-design: true
